name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  trigger:
    strategy:
      matrix:
        include:
          - context: alpine3.14
            tags: |
              nightly-alpine3.14
              nightly-alpine
          - context: bullseye
            tags: |
              nightly-bullseye
          - context: bullseye/slim
            tags: |
              nightly-bullseye-slim
          - context: buster
            tags: |
              value=nightly
              value=nightly-buster
          - context: buster/slim
            tags: |
              nightly-slim
              nightly-buster-slim

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: rustopsbot
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/rust-lang/rust
            rustlang/rust
          tags: ${{ matrix.tags }}

      - uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
